### ISSUE TITLE
Template django_messages

### ISSUE THREAD

**Issue by Azelphur** [Azelphur-Servers/game.azelphur.com#2]
Hi MonsterKiller, as per our previous discussion I've added django_messages, which adds private messaging support to DjangoBB.

It resides at /messages/ and you can see the templates for it at https://github.com/Azelphur/django-messages/tree/master/django_messages/templates

**Comment by RobAWarner** [comment]
Done in dfc0c69751a3784f850b5425c755c0e6d83e6cf4
